/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_guidoscore */

#ifndef _Included_guidoengine_guidoscore
#define _Included_guidoengine_guidoscore
#ifdef __cplusplus
extern "C" {
#endif
#undef guidoengine_guidoscore_kNoBB
#define guidoengine_guidoscore_kNoBB 0L
#undef guidoengine_guidoscore_kPageBB
#define guidoengine_guidoscore_kPageBB 1L
#undef guidoengine_guidoscore_kSystemsBB
#define guidoengine_guidoscore_kSystemsBB 2L
#undef guidoengine_guidoscore_kSystemsSliceBB
#define guidoengine_guidoscore_kSystemsSliceBB 4L
#undef guidoengine_guidoscore_kStavesBB
#define guidoengine_guidoscore_kStavesBB 8L
#undef guidoengine_guidoscore_kMeasureBB
#define guidoengine_guidoscore_kMeasureBB 16L
#undef guidoengine_guidoscore_kEventsBB
#define guidoengine_guidoscore_kEventsBB 32L
/*
 * Class:     guidoengine_guidoscore
 * Method:    ParseFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_ParseFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     guidoengine_guidoscore
 * Method:    ParseString
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_ParseString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     guidoengine_guidoscore
 * Method:    AR2GR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_AR2GR__
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    AR2GR
 * Signature: (Lguidoengine/guidolayout;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_AR2GR__Lguidoengine_guidolayout_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    AR2MIDIFile
 * Signature: (Ljava/lang/String;Lguidoengine/guido2midiparams;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_AR2MIDIFile
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    SVGExport
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_guidoengine_guidoscore_SVGExport
  (JNIEnv *, jobject, jint);

/*
 * Class:     guidoengine_guidoscore
 * Method:    UpdateGR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_UpdateGR__
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    UpdateGR
 * Signature: (Lguidoengine/guidolayout;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_UpdateGR__Lguidoengine_guidolayout_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    ResizePageToMusic
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_ResizePageToMusic
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    FreeAR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscore_FreeAR
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    FreeGR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscore_FreeGR
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetBitmap
 * Signature: ([IIILguidoengine/guidodrawdesc;Lguidoengine/guidopaint;Ljava/awt/Color;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetBitmap
  (JNIEnv *, jobject, jintArray, jint, jint, jobject, jobject, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetPageFormat
 * Signature: (ILguidoengine/guidopageformat;)V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscore_GetPageFormat
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    MarkVoice
 * Signature: (ILguidoengine/guidodate;Lguidoengine/guidodate;III)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_MarkVoice
  (JNIEnv *, jobject, jint, jobject, jobject, jint, jint, jint);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetPageCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetPageCount
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetDuration
 * Signature: (Lguidoengine/guidodate;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetDuration
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetPageDate
 * Signature: (ILguidoengine/guidodate;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetPageDate
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    FindEventPage
 * Signature: (Lguidoengine/guidodate;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_FindEventPage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    FindPageAt
 * Signature: (Lguidoengine/guidodate;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_FindPageAt
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetMap
 * Signature: (IFFILguidoengine/mapcollector;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetMap
  (JNIEnv *, jobject, jint, jfloat, jfloat, jint, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetTimeMap
 * Signature: (Lguidoengine/timemapcollector;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetTimeMap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    DrawBoundingBoxes
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscore_DrawBoundingBoxes
  (JNIEnv *, jobject, jint);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetDrawBoundingBoxes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetDrawBoundingBoxes
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscore_Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
