/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_guidopaint */

#ifndef _Included_guidoengine_guidopaint
#define _Included_guidoengine_guidopaint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     guidoengine_guidopaint
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidopaint_Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
