/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_guido2midiparams */

#include "guidoengine_guido2midiparams.h"
#include "javaIDs.h"

jfieldID gTempoID, gTicksID, gChanID;
jfieldID gIntensityID, gAccentFactorID, gMarcatoFactorID;
jfieldID gDFactorID, gStaccatoFactorID, gSlurFactorID, gTenutoFactorID, gFermataFactorID;
jfieldID gVoice2ChanID;

/*
 * Class:     guidoengine_guido2midiparams
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guido2midiparams_Init
  (JNIEnv * env, jclass cls)
{
	if (!getID (env, cls, gTempoID, "fTempo", "I")) return;
	if (!getID (env, cls, gTicksID, "fTicks", "I")) return;
	if (!getID (env, cls, gChanID, "fChan", "I")) return;

	if (!getID (env, cls, gIntensityID, "fIntensity", "F")) return;
	if (!getID (env, cls, gAccentFactorID, "fAccentFactor", "F")) return;
	if (!getID (env, cls, gMarcatoFactorID, "fMarcatoFactor", "F")) return;

	if (!getID (env, cls, gDFactorID, "fDFactor", "F")) return;
	if (!getID (env, cls, gStaccatoFactorID, "fStaccatoFactor", "F")) return;
	if (!getID (env, cls, gSlurFactorID, "fSlurFactor", "F")) return;
	if (!getID (env, cls, gTenutoFactorID, "fTenutoFactor", "F")) return;
	if (!getID (env, cls, gFermataFactorID, "fFermataFactor", "F")) return;

	if (!getID (env, cls, gVoice2ChanID, "fVoice2Chan", "[I")) return;
}
