/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_guidoelementinfo */

#ifndef _Included_guidoengine_guidoelementinfo
#define _Included_guidoengine_guidoelementinfo
#ifdef __cplusplus
extern "C" {
#endif
#undef guidoengine_guidoelementinfo_kNote
#define guidoengine_guidoelementinfo_kNote 1L
#undef guidoengine_guidoelementinfo_kRest
#define guidoengine_guidoelementinfo_kRest 2L
#undef guidoengine_guidoelementinfo_kEmpty
#define guidoengine_guidoelementinfo_kEmpty 3L
#undef guidoengine_guidoelementinfo_kBar
#define guidoengine_guidoelementinfo_kBar 4L
#undef guidoengine_guidoelementinfo_kRepeatBegin
#define guidoengine_guidoelementinfo_kRepeatBegin 5L
#undef guidoengine_guidoelementinfo_kRepeatEnd
#define guidoengine_guidoelementinfo_kRepeatEnd 6L
#undef guidoengine_guidoelementinfo_kStaff
#define guidoengine_guidoelementinfo_kStaff 7L
#undef guidoengine_guidoelementinfo_kSystemSlice
#define guidoengine_guidoelementinfo_kSystemSlice 8L
#undef guidoengine_guidoelementinfo_kSystem
#define guidoengine_guidoelementinfo_kSystem 9L
#undef guidoengine_guidoelementinfo_kPage
#define guidoengine_guidoelementinfo_kPage 10L
/*
 * Class:     guidoengine_guidoelementinfo
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoelementinfo_Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
