/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_guidolayout */

#ifndef _Included_guidoengine_guidolayout
#define _Included_guidoengine_guidolayout
#ifdef __cplusplus
extern "C" {
#endif
#undef guidoengine_guidolayout_kAutoDistrib
#define guidoengine_guidolayout_kAutoDistrib 1L
#undef guidoengine_guidolayout_kAlwaysDistrib
#define guidoengine_guidolayout_kAlwaysDistrib 2L
#undef guidoengine_guidolayout_kNeverDistrib
#define guidoengine_guidolayout_kNeverDistrib 3L
/*
 * Class:     guidoengine_guidolayout
 * Method:    GetDefault
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidolayout_GetDefault
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidolayout
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidolayout_Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
