/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_guidosegment */

#ifndef _Included_guidoengine_guidosegment
#define _Included_guidoengine_guidosegment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     guidoengine_guidosegment
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidosegment_Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
