/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_guidopageformat */

#ifndef _Included_guidoengine_guidopageformat
#define _Included_guidoengine_guidopageformat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     guidoengine_guidopageformat
 * Method:    GetDefault
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidopageformat_GetDefault
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidopageformat
 * Method:    SetDefault
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidopageformat_SetDefault
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidopageformat
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidopageformat_Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
