#!/bin/sh
#

TARGET=$1
CURR=$(otool -L $TARGET | grep GUIDOEngine.framework | grep compatibility | cut -d ' ' -f 1 | sed 's/^[ 	]*//')
NEW=/Library/Frameworks/GUIDOEngine.framework/Versions/C/GUIDOEngine
install_name_tool -change $CURR $NEW $TARGET

NEWJNI=libjniGUIDOEngine.dylib
install_name_tool -id $NEWJNI $TARGET

otool -L $TARGET

exit 0
