/*
	GUIDO Library
	Copyright (C) 2002  Holger Hoos, Juergen Kilian, Kai Renz

	This library is free software; you can redistribute it and/or
	modify it under the terms of the GNU Lesser General Public
	License as published by the Free Software Foundation; either
	version 2.1 of the License, or (at your option) any later version.

	This library is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
	Lesser General Public License for more details.

	You should have received a copy of the GNU Lesser General Public
	License along with this library; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

*/

#ifndef CHelpDialog_H
#define CHelpDialog_H

#if _MSC_VER > 1000
#pragma once
#endif

#include "resource.h"

class CHelpDialog : public CDialog
{
	// construction
	public:
		CHelpDialog(CWnd* pParent = NULL);   // Standardconstructor

	// Dialogboxdata
		//{{AFX_DATA(CHelpDialog)
		enum { IDD = IDD_HELPDIALOG };
		CString	m_helptxt;
		//}}AFX_DATA


	// overrides
		// virtual overrides generated by the class wizzar
		//{{AFX_VIRTUAL(CHelpDialog)
		protected:
		virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV-support
		//}}AFX_VIRTUAL

	// implementation
	protected:

		// generated message maps 	//{{AFX_MSG(CHelpDialog)
			// HINWEIS: Der Klassen-Assistent fügt hier Member-Funktionen ein
		//}}AFX_MSG
		DECLARE_MESSAGE_MAP()
};


#endif
