/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_rectangle */

#ifndef _Included_guidoengine_rectangle
#define _Included_guidoengine_rectangle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     guidoengine_rectangle
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_rectangle_Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
