/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_guidodate */

#ifndef _Included_guidoengine_guidodate
#define _Included_guidoengine_guidodate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     guidoengine_guidodate
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidodate_Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
