/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_timemapcollector */

#ifndef _Included_guidoengine_timemapcollector
#define _Included_guidoengine_timemapcollector
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
