/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_guidorect */

#ifndef _Included_guidoengine_guidorect
#define _Included_guidoengine_guidorect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     guidoengine_guidorect
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidorect_Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
