/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_guidoscorebase */

#ifndef _Included_guidoengine_guidoscorebase
#define _Included_guidoengine_guidoscorebase
#ifdef __cplusplus
extern "C" {
#endif
#undef guidoengine_guidoscorebase_kNoBB
#define guidoengine_guidoscorebase_kNoBB 0L
#undef guidoengine_guidoscorebase_kPageBB
#define guidoengine_guidoscorebase_kPageBB 1L
#undef guidoengine_guidoscorebase_kSystemsBB
#define guidoengine_guidoscorebase_kSystemsBB 2L
#undef guidoengine_guidoscorebase_kSystemsSliceBB
#define guidoengine_guidoscorebase_kSystemsSliceBB 4L
#undef guidoengine_guidoscorebase_kStavesBB
#define guidoengine_guidoscorebase_kStavesBB 8L
#undef guidoengine_guidoscorebase_kMeasureBB
#define guidoengine_guidoscorebase_kMeasureBB 16L
#undef guidoengine_guidoscorebase_kEventsBB
#define guidoengine_guidoscorebase_kEventsBB 32L
/*
 * Class:     guidoengine_guidoscorebase
 * Method:    ParseFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_ParseFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    ParseString
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_ParseString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    AR2GR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_AR2GR__
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    AR2GR
 * Signature: (Lguidoengine/guidolayout;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_AR2GR__Lguidoengine_guidolayout_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    AR2MIDIFile
 * Signature: (Ljava/lang/String;Lguidoengine/guido2midiparams;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_AR2MIDIFile
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    AbstractExport
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_guidoengine_guidoscorebase_AbstractExport
  (JNIEnv *, jobject, jint);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    BinaryExport
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_guidoengine_guidoscorebase_BinaryExport
  (JNIEnv *, jobject, jint);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    GR2SVG
 * Signature: (IZLjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_guidoengine_guidoscorebase_GR2SVG
  (JNIEnv *, jobject, jint, jboolean, jstring, jint);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    SVGExport
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_guidoengine_guidoscorebase_SVGExport
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    SVGExportWithFontSpec
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_guidoengine_guidoscorebase_SVGExportWithFontSpec
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    UpdateGR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_UpdateGR__
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    UpdateGR
 * Signature: (Lguidoengine/guidolayout;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_UpdateGR__Lguidoengine_guidolayout_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    ResizePageToMusic
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_ResizePageToMusic
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    FreeAR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscorebase_FreeAR
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    FreeGR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscorebase_FreeGR
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    GetPageFormat
 * Signature: (ILguidoengine/guidopageformat;)V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscorebase_GetPageFormat
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    MarkVoice
 * Signature: (ILguidoengine/guidodate;Lguidoengine/guidodate;III)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_MarkVoice
  (JNIEnv *, jobject, jint, jobject, jobject, jint, jint, jint);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    GetPageCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_GetPageCount
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    GetSystemCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_GetSystemCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    CountVoices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_CountVoices
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    GetDuration
 * Signature: (Lguidoengine/guidodate;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_GetDuration
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    GetPageDate
 * Signature: (ILguidoengine/guidodate;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_GetPageDate
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    FindEventPage
 * Signature: (Lguidoengine/guidodate;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_FindEventPage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    FindPageAt
 * Signature: (Lguidoengine/guidodate;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_FindPageAt
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    GetMap
 * Signature: (IFFILguidoengine/mapcollector;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_GetMap
  (JNIEnv *, jobject, jint, jfloat, jfloat, jint, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    GetTimeMap
 * Signature: (Lguidoengine/timemapcollector;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_GetTimeMap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    GetPageMap
 * Signature: (IFFLguidoengine/guidoscoremapbase;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_GetPageMap
  (JNIEnv *, jobject, jint, jfloat, jfloat, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    GetStaffMap
 * Signature: (IFFILguidoengine/guidoscoremapbase;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_GetStaffMap
  (JNIEnv *, jobject, jint, jfloat, jfloat, jint, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    GetVoiceMap
 * Signature: (IFFILguidoengine/guidoscoremapbase;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_GetVoiceMap
  (JNIEnv *, jobject, jint, jfloat, jfloat, jint, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    GetSystemMap
 * Signature: (IFFLguidoengine/guidoscoremapbase;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_GetSystemMap
  (JNIEnv *, jobject, jint, jfloat, jfloat, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    DrawBoundingBoxes
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscorebase_DrawBoundingBoxes
  (JNIEnv *, jobject, jint);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    GetDrawBoundingBoxes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_GetDrawBoundingBoxes
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    OpenParser
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscorebase_OpenParser
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    CloseParser
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_CloseParser
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    GetStream
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_guidoengine_guidoscorebase_GetStream
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    File2AR
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_File2AR
  (JNIEnv *, jobject, jstring);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    String2AR
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_String2AR
  (JNIEnv *, jobject, jstring);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    Stream2AR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_Stream2AR
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    ParserGetErrorCode
 * Signature: ()Lguidoengine/parserError;
 */
JNIEXPORT jobject JNICALL Java_guidoengine_guidoscorebase_ParserGetErrorCode
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    OpenStream
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscorebase_OpenStream
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    CloseStream
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_CloseStream
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    WriteStream
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_WriteStream
  (JNIEnv *, jobject, jstring);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    ResetStream
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscorebase_ResetStream
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscorebase
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscorebase_Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
