/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_parserError */

#ifndef _Included_guidoengine_parserError
#define _Included_guidoengine_parserError
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     guidoengine_parserError
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_parserError_Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
