/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_guidoscore */

#ifndef _Included_guidoengine_guidoscore
#define _Included_guidoengine_guidoscore
#ifdef __cplusplus
extern "C" {
#endif
#undef guidoengine_guidoscore_kNoBB
#define guidoengine_guidoscore_kNoBB 0L
#undef guidoengine_guidoscore_kPageBB
#define guidoengine_guidoscore_kPageBB 1L
#undef guidoengine_guidoscore_kSystemsBB
#define guidoengine_guidoscore_kSystemsBB 2L
#undef guidoengine_guidoscore_kSystemsSliceBB
#define guidoengine_guidoscore_kSystemsSliceBB 4L
#undef guidoengine_guidoscore_kStavesBB
#define guidoengine_guidoscore_kStavesBB 8L
#undef guidoengine_guidoscore_kMeasureBB
#define guidoengine_guidoscore_kMeasureBB 16L
#undef guidoengine_guidoscore_kEventsBB
#define guidoengine_guidoscore_kEventsBB 32L
/*
 * Class:     guidoengine_guidoscore
 * Method:    GetBitmap
 * Signature: ([IIILguidoengine/guidodrawdesc;Lguidoengine/guidopaint;Ljava/awt/Color;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetBitmap
  (JNIEnv *, jobject, jintArray, jint, jint, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
