/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_guidopianoroll */

#ifndef _Included_guidoengine_guidopianoroll
#define _Included_guidoengine_guidopianoroll
#ifdef __cplusplus
extern "C" {
#endif
#undef guidoengine_guidopianoroll_kCLine
#define guidoengine_guidopianoroll_kCLine 1L
#undef guidoengine_guidopianoroll_kCSharpLine
#define guidoengine_guidopianoroll_kCSharpLine 2L
#undef guidoengine_guidopianoroll_kDLine
#define guidoengine_guidopianoroll_kDLine 4L
#undef guidoengine_guidopianoroll_kDSharpLine
#define guidoengine_guidopianoroll_kDSharpLine 8L
#undef guidoengine_guidopianoroll_kELine
#define guidoengine_guidopianoroll_kELine 16L
#undef guidoengine_guidopianoroll_kFLine
#define guidoengine_guidopianoroll_kFLine 32L
#undef guidoengine_guidopianoroll_kFSharpLine
#define guidoengine_guidopianoroll_kFSharpLine 64L
#undef guidoengine_guidopianoroll_kGLine
#define guidoengine_guidopianoroll_kGLine 128L
#undef guidoengine_guidopianoroll_kGSharpLine
#define guidoengine_guidopianoroll_kGSharpLine 256L
#undef guidoengine_guidopianoroll_kALine
#define guidoengine_guidopianoroll_kALine 512L
#undef guidoengine_guidopianoroll_kASharpLine
#define guidoengine_guidopianoroll_kASharpLine 1024L
#undef guidoengine_guidopianoroll_kBLine
#define guidoengine_guidopianoroll_kBLine 2048L
#undef guidoengine_guidopianoroll_kAutoLines
#define guidoengine_guidopianoroll_kAutoLines 0L
#undef guidoengine_guidopianoroll_kNoLine
#define guidoengine_guidopianoroll_kNoLine -1L
#undef guidoengine_guidopianoroll_kSimplePianoRoll
#define guidoengine_guidopianoroll_kSimplePianoRoll 0L
#undef guidoengine_guidopianoroll_kTrajectoryPianoRoll
#define guidoengine_guidopianoroll_kTrajectoryPianoRoll 1L
/*
 * Class:     guidoengine_guidopianoroll
 * Method:    GetBitmap
 * Signature: ([IIILguidoengine/guidopaint;Ljava/awt/Color;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidopianoroll_GetBitmap
  (JNIEnv *, jobject, jintArray, jint, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
