/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_limitparams */

#ifndef _Included_guidoengine_limitparams
#define _Included_guidoengine_limitparams
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     guidoengine_limitparams
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_limitparams_Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
