/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_guidoscoremapbase */

#ifndef _Included_guidoengine_guidoscoremapbase
#define _Included_guidoengine_guidoscoremapbase
#ifdef __cplusplus
extern "C" {
#endif
#undef guidoengine_guidoscoremapbase_kGuidoPage
#define guidoengine_guidoscoremapbase_kGuidoPage 0L
#undef guidoengine_guidoscoremapbase_kGuidoSystem
#define guidoengine_guidoscoremapbase_kGuidoSystem 1L
#undef guidoengine_guidoscoremapbase_kGuidoSystemSlice
#define guidoengine_guidoscoremapbase_kGuidoSystemSlice 2L
#undef guidoengine_guidoscoremapbase_kGuidoStaff
#define guidoengine_guidoscoremapbase_kGuidoStaff 3L
#undef guidoengine_guidoscoremapbase_kGuidoBar
#define guidoengine_guidoscoremapbase_kGuidoBar 4L
#undef guidoengine_guidoscoremapbase_kGuidoEvent
#define guidoengine_guidoscoremapbase_kGuidoEvent 5L
/*
 * Class:     guidoengine_guidoscoremapbase
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscoremapbase_disposeNative
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscoremapbase
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscoremapbase_size
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscoremapbase
 * Method:    get
 * Signature: (ILguidoengine/guidosegment;Lguidoengine/guidorect;)Z
 */
JNIEXPORT jboolean JNICALL Java_guidoengine_guidoscoremapbase_get
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     guidoengine_guidoscoremapbase
 * Method:    getTime
 * Signature: (Lguidoengine/guidodate;Lguidoengine/guidosegment;Lguidoengine/guidorect;)Z
 */
JNIEXPORT jboolean JNICALL Java_guidoengine_guidoscoremapbase_getTime
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     guidoengine_guidoscoremapbase
 * Method:    getPoint
 * Signature: (FFLguidoengine/guidosegment;Lguidoengine/guidorect;)Z
 */
JNIEXPORT jboolean JNICALL Java_guidoengine_guidoscoremapbase_getPoint
  (JNIEnv *, jobject, jfloat, jfloat, jobject, jobject);

/*
 * Class:     guidoengine_guidoscoremapbase
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscoremapbase_Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
