/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_guidoscoremap */

#ifndef _Included_guidoengine_guidoscoremap
#define _Included_guidoengine_guidoscoremap
#ifdef __cplusplus
extern "C" {
#endif
#undef guidoengine_guidoscoremap_kGuidoPage
#define guidoengine_guidoscoremap_kGuidoPage 0L
#undef guidoengine_guidoscoremap_kGuidoSystem
#define guidoengine_guidoscoremap_kGuidoSystem 1L
#undef guidoengine_guidoscoremap_kGuidoSystemSlice
#define guidoengine_guidoscoremap_kGuidoSystemSlice 2L
#undef guidoengine_guidoscoremap_kGuidoStaff
#define guidoengine_guidoscoremap_kGuidoStaff 3L
#undef guidoengine_guidoscoremap_kGuidoBar
#define guidoengine_guidoscoremap_kGuidoBar 4L
#undef guidoengine_guidoscoremap_kGuidoEvent
#define guidoengine_guidoscoremap_kGuidoEvent 5L
#ifdef __cplusplus
}
#endif
#endif
