/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_guidodrawdesc */

#ifndef _Included_guidoengine_guidodrawdesc
#define _Included_guidoengine_guidodrawdesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     guidoengine_guidodrawdesc
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidodrawdesc_Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
