/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_mapcollector */

#ifndef _Included_guidoengine_mapcollector
#define _Included_guidoengine_mapcollector
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
