/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_guidoscore */

#ifndef _Included_guidoengine_guidoscore
#define _Included_guidoengine_guidoscore
#ifdef __cplusplus
extern "C" {
#endif
#undef guidoengine_guidoscore_kNoBB
#define guidoengine_guidoscore_kNoBB 0L
#undef guidoengine_guidoscore_kPageBB
#define guidoengine_guidoscore_kPageBB 1L
#undef guidoengine_guidoscore_kSystemsBB
#define guidoengine_guidoscore_kSystemsBB 2L
#undef guidoengine_guidoscore_kSystemsSliceBB
#define guidoengine_guidoscore_kSystemsSliceBB 4L
#undef guidoengine_guidoscore_kStavesBB
#define guidoengine_guidoscore_kStavesBB 8L
#undef guidoengine_guidoscore_kMeasureBB
#define guidoengine_guidoscore_kMeasureBB 16L
#undef guidoengine_guidoscore_kEventsBB
#define guidoengine_guidoscore_kEventsBB 32L
/*
 * Class:     guidoengine_guidoscore
 * Method:    ParseFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_ParseFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     guidoengine_guidoscore
 * Method:    ParseString
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_ParseString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     guidoengine_guidoscore
 * Method:    AR2GR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_AR2GR__
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    AR2GR
 * Signature: (Lguidoengine/guidolayout;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_AR2GR__Lguidoengine_guidolayout_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    AR2MIDIFile
 * Signature: (Ljava/lang/String;Lguidoengine/guido2midiparams;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_AR2MIDIFile
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    BinaryExport
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_guidoengine_guidoscore_BinaryExport
  (JNIEnv *, jobject, jint);

/*
 * Class:     guidoengine_guidoscore
 * Method:    SVGExport
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_guidoengine_guidoscore_SVGExport
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     guidoengine_guidoscore
 * Method:    SVGExportWithFontSpec
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_guidoengine_guidoscore_SVGExportWithFontSpec
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     guidoengine_guidoscore
 * Method:    UpdateGR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_UpdateGR__
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    UpdateGR
 * Signature: (Lguidoengine/guidolayout;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_UpdateGR__Lguidoengine_guidolayout_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    ResizePageToMusic
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_ResizePageToMusic
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    FreeAR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscore_FreeAR
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    FreeGR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscore_FreeGR
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetBitmap
 * Signature: ([IIILguidoengine/guidodrawdesc;Lguidoengine/guidopaint;Ljava/awt/Color;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetBitmap
  (JNIEnv *, jobject, jintArray, jint, jint, jobject, jobject, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetPageFormat
 * Signature: (ILguidoengine/guidopageformat;)V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscore_GetPageFormat
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    MarkVoice
 * Signature: (ILguidoengine/guidodate;Lguidoengine/guidodate;III)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_MarkVoice
  (JNIEnv *, jobject, jint, jobject, jobject, jint, jint, jint);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetPageCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetPageCount
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetSystemCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetSystemCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     guidoengine_guidoscore
 * Method:    CountVoices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_CountVoices
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetDuration
 * Signature: (Lguidoengine/guidodate;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetDuration
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetPageDate
 * Signature: (ILguidoengine/guidodate;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetPageDate
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    FindEventPage
 * Signature: (Lguidoengine/guidodate;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_FindEventPage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    FindPageAt
 * Signature: (Lguidoengine/guidodate;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_FindPageAt
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetMap
 * Signature: (IFFILguidoengine/mapcollector;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetMap
  (JNIEnv *, jobject, jint, jfloat, jfloat, jint, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetTimeMap
 * Signature: (Lguidoengine/timemapcollector;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetTimeMap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetPageMap
 * Signature: (IFFLguidoengine/guidoscoremap;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetPageMap
  (JNIEnv *, jobject, jint, jfloat, jfloat, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetStaffMap
 * Signature: (IFFILguidoengine/guidoscoremap;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetStaffMap
  (JNIEnv *, jobject, jint, jfloat, jfloat, jint, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetVoiceMap
 * Signature: (IFFILguidoengine/guidoscoremap;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetVoiceMap
  (JNIEnv *, jobject, jint, jfloat, jfloat, jint, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetSystemMap
 * Signature: (IFFLguidoengine/guidoscoremap;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetSystemMap
  (JNIEnv *, jobject, jint, jfloat, jfloat, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    DrawBoundingBoxes
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscore_DrawBoundingBoxes
  (JNIEnv *, jobject, jint);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetDrawBoundingBoxes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_GetDrawBoundingBoxes
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    OpenParser
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscore_OpenParser
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    CloseParser
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_CloseParser
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    GetStream
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_guidoengine_guidoscore_GetStream
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    File2AR
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscore_File2AR
  (JNIEnv *, jobject, jstring);

/*
 * Class:     guidoengine_guidoscore
 * Method:    String2AR
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscore_String2AR
  (JNIEnv *, jobject, jstring);

/*
 * Class:     guidoengine_guidoscore
 * Method:    Stream2AR
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscore_Stream2AR
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    ParserGetErrorCode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscore_ParserGetErrorCode
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    OpenStream
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscore_OpenStream
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    CloseStream
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_CloseStream
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    WriteStream
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_WriteStream
  (JNIEnv *, jobject, jstring);

/*
 * Class:     guidoengine_guidoscore
 * Method:    ResetStream
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_guidoengine_guidoscore_ResetStream
  (JNIEnv *, jobject);

/*
 * Class:     guidoengine_guidoscore
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guidoscore_Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
