/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class guidoengine_guido2midiparams */

#ifndef _Included_guidoengine_guido2midiparams
#define _Included_guidoengine_guido2midiparams
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     guidoengine_guido2midiparams
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_guidoengine_guido2midiparams_Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
