#!/bin/sh
#

##########################################
function makeparams {

	file=$1
cat <<!

### Parameters
 
| Name        	| Type   | Description    | Default value  | Optional |
| :------------ |:-------| :--------------| :------------- | :--------|  
!
  	cat $file | grep -v "="
  	echo
  	echo "<br />"
  	echo
}

##########################################
function maketag {
	tag=$1
	echo
	printf "## \\%s\n" $tag

cat <<!

-------

### Description

| Name | Variants | Type | Notation element |
| :----| :--------| :----| :----------------|
| \\$tag |

!
	makeparams $tag.txt
}

##########################################
function makefile {
	group=$1
	folder=$2
	file=$folder/$(echo $group | sed 's/-//g').md
	label=$(echo $group | sed 's/-/ /g')
	echo "Creating chapter $label in $file"
cat <<! > $file
{!references.ref!}

# $label

!
}


##########################################
echo Building files
for a in $(cat tags.txt | cut -d':' -f 2 | sort -u | sed 's/ /-/g')
do
	makefile $a "docs/refs/tags"
done

echo 

awk -f tagsfiles.awk TagParameters.txt 
cd params
for a in *.txt
do
	tag=$(basename $a .txt)
 	dest=$(grep $tag ../tags.txt | cut -d ':' -f 2 | sort -u | sed 's/ //g')
 	file=../docs/refs/tags/$dest.md
 	echo Insert tag $tag in $file
 	maketag $tag >> $file
 	
done
