


all:
	$(MAKE) -C FontMetrics/build
	$(MAKE) -C GuidoFontMetrics/build
	$(MAKE) -C GuidoQtFontViewer/build


clean:
	$(MAKE) -C FontMetrics/build clean
	$(MAKE) -C GuidoFontMetrics/build clean
	$(MAKE) -C GuidoQtFontViewer/build clean
