


all:
	make -C FontMetrics/build
	make -C GuidoFontMetrics/build
	make -C GuidoQtFontViewer/build


clean:
	make -C FontMetrics/build clean
	make -C GuidoFontMetrics/build clean
	make -C GuidoQtFontViewer/build clean
