#!/bin/sh
#

APP=$1.app/Contents/MacOS/$1
LOCAL=$(pwd)
CURR=$(otool -L $APP | grep GUIDOEngine | grep compatibility | cut -d ' ' -f 1 | sed 's/^[ 	]*//')
NEW=$(echo $CURR | sed -e 's/..*\/GUIDOEngine.framework/@executable_path\/..\/Frameworks\/GUIDOEngine.framework/')

echo changing path:
echo "   $CURR"
echo to
echo "   $NEW"

install_name_tool -id $NEW $APP
install_name_tool -change $CURR $NEW $APP

NEW=$(otool -L $APP | grep GUIDOEngine | grep compatibility | cut -d ' ' -f 1 | sed 's/^[ 	]*//')

exit 0
