#####################################################################
# Automatically generated by qmake (2.01a) mar. avr. 22 10:38:30 2008
#####################################################################

TEMPLATE = app
DESTDIR = ../bin
DEPENDPATH += .
INCLUDEPATH += .
win32 {
	TEMPLATE = vcapp
}
macx:QMAKE_MAC_SDK = macosx10.9


# Input
HEADERS += QFontDisplayer.h
SOURCES += main.cpp QFontDisplayer.cpp
QT += widgets 
