/*
	GUIDO Library
	Copyright (C) 2002  Holger Hoos, Juergen Kilian, Kai Renz

	This library is free software; you can redistribute it and/or
	modify it under the terms of the GNU Lesser General Public
	License as published by the Free Software Foundation; either
	version 2.1 of the License, or (at your option) any later version.

	This library is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
	Lesser General Public License for more details.

	You should have received a copy of the GNU Lesser General Public
	License along with this library; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

*/
#if !defined(AFX_EXPORTGIFDIALOG_H__8D7359D9_2694_4660_A9AC_A9580997154F__INCLUDED_)
#define AFX_EXPORTGIFDIALOG_H__8D7359D9_2694_4660_A9AC_A9580997154F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// ExportGifDialog.h : header-file
//
#include "resource.h"

/////////////////////////////////////////////////////////////////////////////
// Dialogbox CExportGifDialog 

class CExportGifDialog : public CDialog
{
// construction
public:
	CExportGifDialog(CWnd* pParent = NULL);   // Standardconstructor

// Dialogboxdata
	//{{AFX_DATA(CExportGifDialog)
	enum { IDD = IDD_EXPORTGIF_DIALOG };
	CEdit	m_ctrl_filename;
	CButton	m_ctrl_selectzoom;
	CEdit	m_ctrl_zoom;
	CEdit	m_ctrl_sizey;
	CEdit	m_ctrl_sizex;
	BOOL	m_adjustpagesize;
	UINT	m_page;
	UINT	m_sizex;
	UINT	m_sizey;
	float	m_zoomfactor;
	CString	m_filename;
	CString	m_pagerange;
	//}}AFX_DATA

	BOOL	m_iszoom;
	int		m_numpages;

// overrides
	// virtual overrides generated by the class wizzar
	//{{AFX_VIRTUAL(CExportGifDialog)
	public:
	virtual BOOL Create(LPCTSTR lpszClassName, LPCTSTR lpszWindowName, DWORD dwStyle, const RECT& rect, CWnd* pParentWnd, UINT nID, CCreateContext* pContext = NULL);
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV-support
	//}}AFX_VIRTUAL

// implementation
protected:

	// generated message maps 	//{{AFX_MSG(CExportGifDialog)
	afx_msg void OnSelectzoom();
	afx_msg void OnSelectsize();
	virtual BOOL OnInitDialog();
	afx_msg void OnSelectfilename();
	afx_msg void OnAdjustpagesize();
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};

//{{AFX_INSERT_LOCATION}}
// MS Visual C++ inserts directly before the previous line additional deklarations

#endif // AFX_EXPORTGIFDIALOG_H__8D7359D9_2694_4660_A9AC_A9580997154F__INCLUDED_
