/*
	GUIDO Library
	Copyright (C) 2002  Holger Hoos, Juergen Kilian, Kai Renz

	This library is free software; you can redistribute it and/or
	modify it under the terms of the GNU Lesser General Public
	License as published by the Free Software Foundation; either
	version 2.1 of the License, or (at your option) any later version.

	This library is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
	Lesser General Public License for more details.

	You should have received a copy of the GNU Lesser General Public
	License along with this library; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

*/
#if !defined(AFX_MDCONVLOG_H__7D3C7A65_3C89_4CD2_BE79_FF7C8A405BC6__INCLUDED_)
#define AFX_MDCONVLOG_H__7D3C7A65_3C89_4CD2_BE79_FF7C8A405BC6__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "resource.h"

/////////////////////////////////////////////////////////////////////////////
// Dialogbox MDConvLog 

class MDConvLog : public CDialog
{
// construction
public:
	MDConvLog(CWnd* pParent = NULL);   // Standardconstructor

// Dialogboxdata
	//{{AFX_DATA(MDConvLog)
	enum { IDD = IDD_MDCONVFAILE };
	CString	m_logtext;
	CString	m_titletext;
	//}}AFX_DATA


// overrides
	// virtual overrides generated by the class wizzar
	//{{AFX_VIRTUAL(MDConvLog)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV-support
	//}}AFX_VIRTUAL

// implementation
protected:

	// generated message maps 	//{{AFX_MSG(MDConvLog)
		// HINWEIS: Der Klassen-Assistent fügt hier Member-Funktionen ein
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};

//{{AFX_INSERT_LOCATION}}
// MS Visual C++ inserts directly before the previous line additional deklarations

#endif // AFX_MDCONVLOG_H__7D3C7A65_3C89_4CD2_BE79_FF7C8A405BC6__INCLUDED_
