/*
	GUIDO Library
	Copyright (C) 2002  Holger Hoos, Juergen Kilian, Kai Renz

	This library is free software; you can redistribute it and/or
	modify it under the terms of the GNU Lesser General Public
	License as published by the Free Software Foundation; either
	version 2.1 of the License, or (at your option) any later version.

	This library is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
	Lesser General Public License for more details.

	You should have received a copy of the GNU Lesser General Public
	License along with this library; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

*/
#if !defined(AFX_MYHTMLVIEW_H__E1F49DE1_B076_11D2_AD0A_0080C75E70DF__INCLUDED_)
#define AFX_MYHTMLVIEW_H__E1F49DE1_B076_11D2_AD0A_0080C75E70DF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// MyHTMLView.h : 
//

/////////////////////////////////////////////////////////////////////////////
// CMyHTMLView HTML-View

#ifndef __AFXEXT_H__
#include <afxext.h>
#endif
#include <afxhtml.h>

class CMyHTMLView : public CHtmlView
{
protected:
	CMyHTMLView();           // protected constructor, is used from dynamic creation
	DECLARE_DYNCREATE(CMyHTMLView)

// HTML-Daten
public:
	//{{AFX_DATA(CMyHTMLView)
		// REMARK: the class wizzard inserts here data elements
	//}}AFX_DATA

// Attribute
public:

// Operationen
public:

// overloads
	// Overrides of virtual functions generated by the class wizzard
	//{{AFX_VIRTUAL(CMyHTMLView)
	public:
	virtual void OnInitialUpdate();
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV-support
	//}}AFX_VIRTUAL

// Implementation
protected:
	virtual ~CMyHTMLView();
#ifdef _DEBUG
	virtual void AssertValid() const;
	virtual void Dump(CDumpContext& dc) const;
#endif

	// Generated functions for messgae conversion
	//{{AFX_MSG(CMyHTMLView)
		// HINWEIS - Hier werden Member-Funktionen vom Klassen-Assistenten hinzugefügt und entfernt.
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};

/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// MS Visual C++ inserts directly before the previous line additional deklarations

#endif // AFX_MYHTMLVIEW_H__E1F49DE1_B076_11D2_AD0A_0080C75E70DF__INCLUDED_
