/*
	GUIDO Library
	Copyright (C) 2002  Holger Hoos, Juergen Kilian, Kai Renz

	This library is free software; you can redistribute it and/or
	modify it under the terms of the GNU Lesser General Public
	License as published by the Free Software Foundation; either
	version 2.1 of the License, or (at your option) any later version.

	This library is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
	Lesser General Public License for more details.

	You should have received a copy of the GNU Lesser General Public
	License along with this library; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

*/
#ifndef AFX_PAGEBUTTON_H__2E54B0E1_73DB_11D2_9307_444553540000__INCLUDED_
#define AFX_PAGEBUTTON_H__2E54B0E1_73DB_11D2_9307_444553540000__INCLUDED_

// PageButton.h : header-file
//

/////////////////////////////////////////////////////////////////////////////
// Fenster CPageButton 

class CPageButton : public CButton
{
// Konstruktion
public:
	CPageButton();

// Attribute
public:

// Operationen
public:

// overrides
	// virtual overrides generated by the class wizzar
	//{{AFX_VIRTUAL(CPageButton)
	//}}AFX_VIRTUAL

// implementation
public:
	virtual ~CPageButton();

	// generated message maps protected:
	//{{AFX_MSG(CPageButton)
	afx_msg void OnSetFocus(CWnd* pOldWnd);
	afx_msg BOOL OnSetCursor(CWnd* pWnd, UINT nHitTest, UINT message);
	//}}AFX_MSG

	DECLARE_MESSAGE_MAP()
};

/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio fügt zusätzliche Deklarationen unmittelbar vor der vorhergehenden Zeile ein.

#endif // AFX_PAGEBUTTON_H__2E54B0E1_73DB_11D2_9307_444553540000__INCLUDED_
