/*
	GUIDO Library
	Copyright (C) 2002  Holger Hoos, Juergen Kilian, Kai Renz

	This library is free software; you can redistribute it and/or
	modify it under the terms of the GNU Lesser General Public
	License as published by the Free Software Foundation; either
	version 2.1 of the License, or (at your option) any later version.

	This library is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
	Lesser General Public License for more details.

	You should have received a copy of the GNU Lesser General Public
	License along with this library; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

*/
#if !defined(AFX_SPACINGDIALOG_H__3050AF78_8984_40C8_B2F6_76593663AC05__INCLUDED_)
#define AFX_SPACINGDIALOG_H__3050AF78_8984_40C8_B2F6_76593663AC05__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif

#include "resource.h"
#include "GUIDOEngine.h"

/////////////////////////////////////////////////////////////////////////////
// Dialogbox CSpacingDialog 

class CSpacingDialog : public CDialog
{
// construction
public:
	CSpacingDialog( GuidoLayoutSettings * settings, CWnd * pParent );

	int m_def_sys_dis_changed;

// Dialogboxdata
	//{{AFX_DATA(CSpacingDialog)
	enum { IDD = IDD_SPACING_PARAMETERS };
	CEdit	m_def_sys_dis_disp;
	CSliderCtrl	m_ctrl_def_sys_dis;
	CEdit	m_ctrl_forcedisplay;
	CSliderCtrl	m_slider;
	int		m_optforceint;
	BOOL	m_optpagefill;
	BOOL	m_specialspacing;
	int		m_def_sys_dis;
	int		m_dis_auto;
	//}}AFX_DATA


// overrides
	// virtual overrides generated by the class wizzar
	//{{AFX_VIRTUAL(CSpacingDialog)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV-support
	//}}AFX_VIRTUAL

// implementation
protected:

	 GuidoLayoutSettings * mSettings;

	// generated message maps 	//{{AFX_MSG(CSpacingDialog)
	virtual BOOL OnInitDialog();
	afx_msg void OnHScroll(UINT nSBCode, UINT nPos, CScrollBar* pScrollBar);
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};

//{{AFX_INSERT_LOCATION}}
// MS Visual C++ inserts directly before the previous line additional deklarations

#endif // AFX_SPACINGDIALOG_H__3050AF78_8984_40C8_B2F6_76593663AC05__INCLUDED_
