/*
	GUIDO Library
	Copyright (C) 2002  Holger Hoos, Juergen Kilian, Kai Renz

	This library is free software; you can redistribute it and/or
	modify it under the terms of the GNU Lesser General Public
	License as published by the Free Software Foundation; either
	version 2.1 of the License, or (at your option) any later version.

	This library is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
	Lesser General Public License for more details.

	You should have received a copy of the GNU Lesser General Public
	License along with this library; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

*/
#if !defined(AFX_ZOOMDIALOG2_H__0744CFE0_AF8F_11D2_AD0A_0080C75E70DF__INCLUDED_)
#define AFX_ZOOMDIALOG2_H__0744CFE0_AF8F_11D2_AD0A_0080C75E70DF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "resource.h"

/////////////////////////////////////////////////////////////////////////////
// Dialogbox CZoomDialog2 

class CZoomDialog2 : public CDialog
{
// construction
public:
	float getZoom(void);
	CZoomDialog2(CWnd *pParent,float p_zoom);
	CZoomDialog2(CWnd* pParent = NULL);   // Standardconstructor

// Dialogboxdata
	//{{AFX_DATA(CZoomDialog2)
	enum { IDD = IDD_ZOOMDIALOG };
	CEdit	m_ZoomEdit;
	CSliderCtrl	m_Slider;
	//}}AFX_DATA


// overrides
	// virtual overrides generated by the class wizzar
	//{{AFX_VIRTUAL(CZoomDialog2)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV-support
	//}}AFX_VIRTUAL

// implementation
protected:
	float zoom;

	// generated message maps 	//{{AFX_MSG(CZoomDialog2)
	virtual BOOL OnInitDialog();
	afx_msg void OnVScroll(UINT nSBCode, UINT nPos, CScrollBar* pScrollBar);
	afx_msg void OnUpdateEditzoom();
	afx_msg void OnChangeEditzoom();
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};

//{{AFX_INSERT_LOCATION}}
// MS Visual C++ inserts directly before the previous line additional deklarations

#endif // AFX_ZOOMDIALOG2_H__0744CFE0_AF8F_11D2_AD0A_0080C75E70DF__INCLUDED_
