#!/bin/sh
#

echo "const char guido2svg[] = {"
cat guido2.svg | \
	sed -e 's/^[ 	]*//' | \
	sed -e "s/\(.\)/'\1', /g" | \
	sed -e 's/\\/\\\\/g'
echo "' ' };"
echo
exit


#echo "const char* guido2svg = \"\\"
#cat guido2.svg | \
#	sed -e 's/\\/\\\\/g' | \
#	sed -e 's/"/\\"/g' | \
#	sed -e 's/^[ 	]*//' | \
#	sed -e 's/$/\\/'
#echo '";'
#echo

#	sed -e 's/^\(..*\)$/\"\1\"/'
