#!/bin/sh
#

font=$1

awk '
BEGIN { p=0 }
/<glyph /,/\/>/ { \
	sub(">", ">\n")
	printf("%s", $0) 
	p=1 }
p == 0
p > 0 { p = 0 }'  $font		| \
	sed -e 's/ glyph-name="[^"]*"//' | \
	grep -v 'glyph..*\.notdef' | \
	grep -v 'glyph..*\.null' | \
	grep -v 'glyph..*nonmarkingreturn' | \
	grep -v 'glyph horiz-adv-x' | \
	grep -v '<glyph $' | \
	grep -v 'glyph..*d="M63 0v800h375v-800h-375zM125 63h250v675h-250v-675z"' | \
	grep -v 'glyph..*d="M468 653l56 -48l-524 -605l-56 48zM-55 639l56 42l481 -639l-56 -42z"'
	
