#!/bin/sh
#

echo "#ifndef _guido2_H_"
echo "#define _guido2_H_"
echo
echo "const char ______src_guido2_svg[] = {"
cat guido2.svg | \
	sed -e "s/\(.\)/'\1', /g" | \
	sed -e 's/\\/\\\\/g' | \
	sed -e "s/'''/'\\\\''/g"
echo "' ' };"
echo
echo "#endif"
echo
exit


#echo "const char* guido2svg = \"\\"
#cat guido2.svg | \
#	sed -e 's/\\/\\\\/g' | \
#	sed -e 's/"/\\"/g' | \
#	sed -e 's/^[ 	]*//' | \
#	sed -e 's/$/\\/'
#echo '";'
#echo

#	sed -e 's/^\(..*\)$/\"\1\"/'
