#!/bin/sh
# 
# GuidoAR project
# version management tool
#

if [ $# -ne 1 ]
then
	echo "usage: version version_num"
	echo "       version_num format: n.n"
	exit 1
fi

ROOT=.
VERSION=$1


echo "moving version number to $VERSION"

CMAKE=$ROOT/build/CMakeLists.txt
echo " updating $CMAKE"
sed "s/\(set ([A-Z]*VERS[^0-9]*\)[0-9]*\.[0-9]*/\1$VERSION/" $CMAKE > TMP$$
mv -f TMP$$ $CMAKE
cmake -G Xcode $ROOT/cmake

DOC=$ROOT/doc/Doxyfile
echo " updating $DOC"
sed "s/\(PROJECT_NUMBER[ 	]*=\)[0-9]*\.[0-9]*/\1$VERSION/" $DOC > TMP$$
mv -f TMP$$ $DOC

DOC=$ROOT/doc/internal/Doxyfile
echo " updating $DOC"
sed "s/\(PROJECT_NUMBER[ 	]*=\)[0-9]*\.[0-9]*/\1$VERSION/" $DOC > TMP$$
mv -f TMP$$ $DOC

echo "==> change manually libguidoar.cpp and libguidoar.rc"
open -t rsrc/libguidoar.rc src/interface/libguidoar.cpp
