#!/bin/sh
#

LOCAL=$(pwd)
while [ $1 ]
do
	APP=$1
	CURR=$(otool -L $APP | grep GUIDOEngine | grep compatibility | cut -d ' ' -f 1 | sed 's/^[ 	]*//')
	NEW=$(echo $CURR | sed -e 's/..*\/GUIDOEngine.framework/@executable_path\/GUIDOEngine.framework/')

	echo changing path:
	echo "   $CURR"
	echo to
	echo "   $NEW"

	install_name_tool -id $NEW $APP
	install_name_tool -change $CURR $NEW $APP

	NEW=$(otool -L $APP | grep GUIDOEngine | grep compatibility | cut -d ' ' -f 1 | sed 's/^[ 	]*//')
	shift
done
exit 0
